# Site settings
name: WardLin's Blog    #博客名称
email: 13825226424@163.com    #邮箱地址
author: WardLin               #作者名
url: http://wardlin.github.io   #个人网站
resume_site: https://github.com/WardLin/Resume.io/    #个人简历网址
github: https://github.com/WardLin/    #github地址
baseurl: ""
description:  talk less and do more
meta_description: 学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: WardLin
highlighter: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : wardlin   #多说账号
    disqus :
        short_name : wardlin   #disqus账号
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light